sudo: required
language: python
env:
  global:
  - secure: V3lYtaVU74vaa3poBxTpy4DgV3nGkfoRXxe8P547xaVSWt/fxZpoekwvuzHNrqoONCRhJCtnJ8M+V/LO0D94ioeCGs0Eve4y18uxF37DZSinrzgfM0DGHPC/WciUmpJ37CmvvAFsa4XSyfpP0KFMgCEP7uKecH1/zeq+4ALqMA2/n9FOxPUKeO80B9YCb8jvHSa6sqMCrJ+xOHPoVh3GFTvHfSw9CeFq5m3TP7s6pdEPjO4gi20NM+Cc/80VGORtD3TJNZkh1263yW4ZoJcRDaaL23lwtKIQ6eQPbYdepTxINqwbIskIu2D7QSgKa1f4nw/jkw9dZwkuE78BCcRStmxdwNd41NWtkYlQFXPW1GUfvXdHmzAe/Wgn1P8sUDeziPxgeu2v5BADMegdKVA4nEq/rd8R+NSpT3BSFwBqEp05sC3q2yBwrE2k3nuBTrZZnBg10MGjQO3Toy6wg6rz1aj4biO695XK+imrxfbA2CEWSPVw4I5fp9ILHpD1w60QuOxU11GLD9ke3Mx3FZVI8lNtIz7WeuKsmOpM0ZnArgRw9aom2cCqpikMof657tJRYu7oWMxet5FzBawaNbUwEeIdX3AnFmtzaoiQocxRX9OoJGiirM+sYitKg0ehSnUaNKIRb7lVtyfnxuz1f2KzAiAIfswohSkALC+j06pUNxQ=
git:
  depth: false
branches:
  only:
  - master
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
pandoc_version: 2.3.1
cache:
  directories:
  - "~/Rlib"
install:
- mkdir -p ~/Rlib
- echo 'R_LIBS=~/Rlib' > .Renviron
- echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
- Rscript -e 'if(!"rmarkdown" %in% rownames(installed.packages())) { install.packages("rmarkdown",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringan" %in% rownames(installed.packages())) { install.packages("xaringan",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringanthemer" %in% rownames(installed.packages())) { install.packages("xaringanthemer",
  dependencies = TRUE) }'
- Rscript -e 'if(!"tinytex" %in% rownames(installed.packages())) { install.packages("tinytex",
  dependencies = TRUE) }'
- Rscript -e 'if(!"scifigure" %in% rownames(installed.packages())) { install.packages("scifigure",
  dependencies = TRUE) }'
- Rscript -e 'if(!"grid" %in% rownames(installed.packages())) { install.packages("grid",
  dependencies = TRUE) }'
- Rscript -e 'if(!"remotes" %in% rownames(installed.packages())) { install.packages("remotes",
  dependencies = TRUE) }'
- Rscript -e 'if(!"icon" %in% rownames(installed.packages())) { remotes::install_github("ropenscilabs/icon")
  }'
- Rscript -e 'tinytex::install_tinytex()'
- Rscript -e 'tinytex::tinytex_root()'
- sudo apt install python3-pip
- pip3 --version
- pip install pyyaml
before_script:
- chmod +x ./website/_build.sh
- chmod +x ./website/_deploy.sh
script:
- "./website/_build.sh"
- "./website/_deploy.sh"
