sudo: required
language: python
env:
  global:
  - secure: "sw66e2l6GYOQOGdD2aoEOYHTtEJfWruWhD3f6SKLG+dzpD+EFc66T7675CXbHXEnGJx/b06YDuTkeFsyTZ0Wkp/ZcJDiNOW5R2oSxfHfEJ5Xa74PbyzALZNshi7W/nxFvHLhmdHUZKQndmvMLwfmPsCvpnG9qmqQS4ow7cZu3hzI8WoweoPkw05pKTGN7JTm1QFKajeMEiHanKYDmjqJ0ujgHE8YyhUhrjXs9YZp0FUGVTjs/I29UOFYtoojjd9PBriFCWJ1kJFrmX9e5hJjq15/2g/qrfeHpkF545+eADNH2DY/xuislPhyGhhFwcWhD3OA0qozTLEx8zr/mhJsjS9xRhdHd7ire+JGGpVBQtoFE/n9H4eUyONM3CiLoCtVFw/uvDEl0XlotzbsgR0dhvFhxT4iZPmfDLq8HtXDj3y491vAXQdG3WmYsC9dRGTIw7IP5h0PcjY0UXY7zrxGwYg/Cvg+YU3SxGGiUOlnEbfVd/PcZjmgRGN9ic8As10bJrKJ3A63cgADn1L1f+C8MHnOFk4f0X+61Kg2jS89IjZCC1xTZO/OE2Te0YQZ9V5wtaal+MnfT6XlHI8/A34ApGMgAEvJtNzRZzqfK699fPcgyMiLg5as28/ftCU+7K1ZANO/HvUCFu6Rhrv0npKs/92Id6VDl2xz/+JYluFc+4g="
git:
  depth: false
branches:
  only:
  - master
addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
    - pandoc
pandoc_version: 2.3.1
cache:
  directories:
  - "~/Rlib"
install:
- mkdir -p ~/Rlib
- echo 'R_LIBS=~/Rlib' > .Renviron
- echo 'options(repos = "http://cran.rstudio.com")' > .Rprofile
- Rscript -e 'if(!"rmarkdown" %in% rownames(installed.packages())) { install.packages("rmarkdown",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringan" %in% rownames(installed.packages())) { install.packages("xaringan",
  dependencies = TRUE) }'
- Rscript -e 'if(!"xaringanthemer" %in% rownames(installed.packages())) { install.packages("xaringanthemer",
  dependencies = TRUE) }'
- Rscript -e 'if(!"tinytex" %in% rownames(installed.packages())) { install.packages("tinytex",
  dependencies = TRUE) }'
- Rscript -e 'if(!"scifigure" %in% rownames(installed.packages())) { install.packages("scifigure",
  dependencies = TRUE) }'
- Rscript -e 'if(!"grid" %in% rownames(installed.packages())) { install.packages("grid",
  dependencies = TRUE) }'
- Rscript -e 'if(!"remotes" %in% rownames(installed.packages())) { install.packages("remotes",
  dependencies = TRUE) }'
- Rscript -e 'if(!"icon" %in% rownames(installed.packages())) { remotes::install_github("ropenscilabs/icon")
  }'
- Rscript -e 'tinytex::install_tinytex()'
- Rscript -e 'tinytex::tinytex_root()'
- sudo apt install python3-pip
- pip3 --version
- pip install pyyaml
before_script:
- chmod +x ./website/_build.sh
- chmod +x ./website/_deploy.sh
script:
- "./website/_build.sh"
- "./website/_deploy.sh"
